### ISSUE TITLE
Hydra jobs continue "building" if npm errors out via napalm 

### ISSUE THREAD

**Issue by paulyoung** [nmattia/napalm#3]
I've experienced this with both `npm install` and `npm run test` (by providing `npmCommands` to `buildPackage`)

Hydra logs end with the `npm ERR! ...` error output that typically appears before `npm` exits with a non-zero exit code, e.g. when a dependency can't be found or a test fails.

**Comment by nmattia** [comment]
It might be that nix is waiting for the registry to shutdown. I’ll take a look on Monday.

**Comment by nmattia** [comment]
Fixed in https://github.com/nmattia/napalm/commit/78cb7d391f14a33a8f7b5cfaa5ff26d97470549c

**Comment by paulyoung** [comment]
Thanks @nmattia!
